The generated files...
git-svn-id: file://localhost/home/tolik/svnrepo/trunk/opencv@354 c5418bc3-7546-4aae-8bad-fa6f2f3e53e6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21465,6 +21465,71 @@ fi
 
 
 
+echo "$as_me:$LINENO: checking for linux/videodev2.h" >&5
+echo $ECHO_N "checking for linux/videodev2.h... $ECHO_C" >&6
+if test "${ac_cv_header_linux_videodev2_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+		#include <asm/types.h>
+		#include <sys/time.h>
+
+
+#include <linux/videodev2.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_header_linux_videodev2_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_header_linux_videodev2_h=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_linux_videodev2_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_videodev2_h" >&6
+if test $ac_cv_header_linux_videodev2_h = yes; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_CAMV4L2
+_ACEOF
+
+                  have_v4l2=yes
+
+else
+   have_v4l2=no
+fi
+
+
+
 setup_swig=no
 # Check whether --enable-python or --disable-python was given.
 if test "${enable_python+set}" = set; then
@@ -23521,6 +23586,7 @@ Configuration:
     Use ffmpeg:               ${have_ffmpeg}
     Use dc1394 & raw1394:     ${have_dc1394}
     Use v4l:                  ${have_v4l}
+    Use v4l2:                 ${have_v4l2}
 
     Build wrappers for
     - Python                  ${enable_python}" >&5
@@ -23539,6 +23605,7 @@ Configuration:
     Use ffmpeg:               ${have_ffmpeg}
     Use dc1394 & raw1394:     ${have_dc1394}
     Use v4l:                  ${have_v4l}
+    Use v4l2:                 ${have_v4l2}
 
     Build wrappers for
     - Python                  ${enable_python}" >&6
